services:
  workspace:
    build: .
    volumes:
      - ./:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
